### ISSUE TITLE
Code for this lesson is already provided

### ISSUE THREAD

**Issue by daniellecroxton** [learn-co-students/js-principles-scope-chain-code-along-v-000#195]
I know this is a 'code-along' so perhaps this is intentional, but all of the code to pass the tests in this lab is provided. The last commit message says 'Copy over existing lesson as a placeholder.'

**Comment by sgharms** [comment]
As of 2018-10-01 this lab runs its tests by running `learn` and does not ship the solution (our apologies). Please open a new issue  [here](https://github.com/learn-co-curriculum/js-principles-scope-chain-code-along/issues) if there is a problem.
