### ISSUE TITLE
Open issue from April still not addressed

### ISSUE THREAD

**Issue by AspenJames** [learn-co-students/js-principles-scope-chain-code-along-v-000#324]
Issue #44 and comments spell out the issue fairly thoroughly, yet this still remains unaddressed. Students are unable to flag issues to increase visibility. @aviflombaum @jmburges

**Comment by sgharms** [comment]
@AspenJames I see these issues are being opened on the learn-co-students branch. [Learn's issue reporting interface](http://help.learn.co/technical-support/improving-learn/raising-an-issue-with-a-lab-or-lesson) _should_ lead issues to be reported on the canonical repo where we will see the issues.

That said, #44 reports two issues:

1. Can't run npm test. I could not replicate this. It ran fine for us in local our local environment.
2. [Lab ships with solution](https://github.com/learn-co-students/js-principles-scope-chain-code-along-v-000/issues/44#issuecomment-401576854) is validated. This will be fixed momentarily.

If 1, above, is still a problem, please open an issue on learn-co-curriculum/js-principles-scope-chain-code-along

Thanks,

Steven
