### ISSUE TITLE
lesson expects passing tests but learn gem doesn't recognize the test included in repo 

### ISSUE THREAD

**Issue by jinstrider2000** [learn-co-students/js-principles-scope-chain-code-along-v-000#44]
Hello, when I run 'learn' in bash, the console gives an error saying there are no tests available, making it impossible to complete. To fix this, I simply deleted the package-lock.json file and added the following lines in package.json:
```js
"scripts": {
"postinstall": "gem install learn-co",
  "test": "node_modules/browser-sync/bin/browser-sync.js start --config node_modules/learn-browser/bs-config.js"
}
```
Also, I updated the value of the "learn-browser" key to "^0.1.13".
With that it worked, I just wanted to alert someone of this.  I submitted a pull request with these changes (last regarding this: the package.json file seems to have other wrong info in it. Seems like it was copy/pasted from another lesson, but I didn't update that stuff).

Finally, I want to suggest that this lesson should actually be excised from the javascript section, since it is essentially a repeat of the [Scope Lab](https://github.com/learn-co-students/js-principles-scope-lab-v-000). Thanks for your consideration!

**Comment by AlliTzadok** [comment]
I made these same changes and although the tests run and pass, they don't link with flatirons learn.co lessons to show that tests have been run.

**Comment by lisaychuang** [comment]
This issue still prevail, the lab is essentially the same as Scope Lab per above.  As of today, tests are still not linked to the lesson.

I've updated the content of `package.json` file per below.  After that, I removed `node_modules` folder and `package-lock.json` file and re-ran `learn` command so that the lab recognize test passing and pull request.

**package.json file**
```js
{
  "name": "javascript-strings-lab",
  "version": "0.1.0",
  "description": "JavaScript Strings Code-along for Learn.co",
  "main": "index.js",
  "scripts": {
    "postinstall": "gem install learn-co",
    "test": "node_modules/browser-sync/bin/browser-sync.js start --config node_modules/learn-browser/bs-config.js"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/learn-co-curriculum/js-principles-scope-chain-code-along-v-000.git"
  },
  "keywords": [
    "learn",
    "flatiron school",
    "javascript",
    "strings",
    "code-along"
  ],
  "author": "Flatiron School",
  "license": "SEE LICENSE IN LICENSE.md",
  "bugs": {
    "url": "https://github.com/learn-co-students/js-principles-scope-chain-code-along-v-000/issues"
  },
  "homepage": "https://github.com/learn-co-students/js-principles-scope-chain-code-along-v-000/blob/master/README.md",
  "devDependencies": {
    "learn-browser": "^0.1.13"
  }
}
```

**Comment by alexisadorn** [comment]
This is still an issue. I followed @lisaychuang 's steps above and was able to get my tests passing.

**Comment by ddhogan** [comment]
I followed the instructions above, and my tests still are not recognized by the learn-co gem.

**Comment by micholi** [comment]
This is still an issue. I followed all the instructions above and can't get the tests to pass. The attemptTwoFavoriteCustomers function seems to break everything. Without it, the remaining tests pass, but when you add it back in, all tests fail.

**Comment by sgharms** [comment]
As of 2018-10-01 this lab runs its tests by running `learn` and does not ship the solution (our apologies). Please open a new issue  [here](https://github.com/learn-co-curriculum/js-principles-scope-chain-code-along/issues) if there is a problem.
